// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://digfkwgrmchsegakdgmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZ2Zrd2dybWNoc2VnYWtkZ21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjgxNTIsImV4cCI6MjA3MjEwNDE1Mn0.wH_TSeiRfz_FnKB8-opZ84nzqX8vwd6kkp0jzPTs9CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});